name: Generate Isometric Contributions

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Clone isometric-contributions-embeds
        run: |
          git clone https://github.com/Spectrewolf8/isometric-contributions-embeds.git
          cd isometric-contributions-embeds
          npm install
          npm run generate -- samuka7abr isometric.svg
          mv isometric.svg ../isometric.svg

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add isometric.svg
          git commit -m "update isometric contributions" || exit 0
          git push