name: Generate Isometric Contributions

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2-dev \
            libjpeg-dev \
            libpango1.0-dev \
            libgif-dev \
            librsvg2-dev \
            pkg-config

      - name: Clone generator
        run: |
          git clone https://github.com/Spectrewolf8/isometric-contributions-embeds.git
          cd isometric-contributions-embeds
          npm install
          npm run generate -- samuka7abr none ../isometric.svg

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add isometric.svg
          git commit -m "update isometric contributions" || echo "no changes"
          git push
